data_process:
  data_base_dir: './valid_permission'
  accounts_dir: 'accounts'
  instructs_dir: 'instructs'
  label_file: 'answer_valid_permission.json'

runtime:
  output_dir: './outputs'
  limit: 1
  samples_per_case: 1
  pass_k: 1

prompt:
  base_prompt_template_path: './prompt/base_prompt_template.txt'
  generation_zero_shot_system_path: './prompt/generation_zero_shot_system.txt'
  generation_one_shot_system_path: './prompt/generation_one_shot_system.txt'
  generation_few_shot_system_path: './prompt/generation_few_shot_system.txt'
  generation_cot_system_path: './prompt/generation_cot_system.txt'
  regenerate_error_repair_path: './prompt/regenerate_error_repair.txt'

llm:
  base_url: 'https://api.siliconflow.cn/v1/chat/completions'
  api_key_env: 'sk-ziwfobfdevetcibhytppdcakzxaenrhvexfdbcznpwtjiqjt'
  request_timeout: 120

  generation_model: 'Qwen/Qwen2.5-Coder-32B-Instruct'
  generation_temperature: 0.1
  generation_max_tokens: 4096
  generate_mode: 0
  regenerate_enabled: false
  regenerate_max_retries: 3